import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  useEffect(() => {
    window.location.href = "/packages";
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Radiant Resort Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contents"></div>
    </div>
  );
}
